# 사용자 정의 파이썬 클래스 개발 방법 학습
1. 주요 키워드 및 기호 : self
- 자바와 비교사 : 데이터 표현 전용 구조의 클래스 

In [1]:
class MyClass2:
    def set(self,v):
        self.value = v
    
    def get(self):
        return self.value
    
    def incr(self):
        self.value += 1
        return get()
    


In [ ]:
class Book:
    def __init__(self, title, author, pages):
        self.title = title
        self.author = author
        self.pages

In [34]:
class UserClass:
    # 생성자
    def __init__(self,data):
        self.instanceVar = data
        print('생성장')
        
    #멤버 변수값 반환 하는 메소드
    def getinstanceVar(self):
        return self.instanceVar
def getinstanceVar2():
    return 'data'

In [35]:
i1 = UserClass('변수')
data = i1.getinstanceVar()
data

생성장


'변수'

In [36]:
data2 = getinstanceVar2()
data2

'data'

In [73]:
class Person:
    def __init__(self,name='haha',age = 20):
        self.name = name
        self.age = age
    def getname(self):
        return self.name
    def setname(self,Name):
        self.name = Name
    def getage(self):
        return self.age
    def setAge(self,Age):
        self.age = Age

In [60]:
jacob = Person('jake')
jacob.getname()
jacob.setname('yark')

In [61]:
jacob.getname()

'yark'

In [62]:
jacob.setname('yo')

In [63]:
jacob.getname()

'yo'

In [76]:
yo = Person()

In [77]:
yo.getname()

'haha'

In [78]:
yo.getage()

20

In [79]:
class Person1:
    def __init__(self):
        self.name = 'hhh'

In [85]:
p = Person1()

In [86]:
p.name = 'jaja'

In [87]:
print(p.name)

jaja


In [110]:
import numpy as np 
a = np.zeros((2,3))
print(type(a))
print(a[0][2])

<class 'numpy.ndarray'>
0.0


In [229]:
"""
벡터값 구하는 클래스를 만든다
"""
import numpy as np

class Vector:
    def __init__(self,x,y,result = np.zeros((2,2))):
        self.x = x
        self.y = y
    def getVector(self):
        result = np.zeros((len(self.x),len(self.y[0])))
        for i in range(len(self.x)):
            for j in range(len(self.y[0])):
                for k in range(len(self.y)):
                    result[i][j] += self.x[i][k] * self.y[k][j]
        print(result)

In [230]:
X = [[1, 2, 3],
     [4 ,5, 6],
     [5, 2, 3],
     [8, 4, 6]]
Y = [[1, 2,4],
     [3 ,4,6],
     [5 ,6,7]]
v = Vector(X,Y)
print(len(Y[0]))

3


In [231]:
v.getVector()

[[22. 28. 37.]
 [49. 64. 88.]
 [26. 36. 53.]
 [50. 68. 98.]]


In [168]:
class Dog:
    name = ""
    age = 0
    color = ""
    bread = ""
    
    def __init__(self,name,age,color,bread):
        self.name = name
        self.age = age
        self.color = color
        self.bread = bread
    def run(self):
        print((self.name) + ":헥헥")
        
    def bark(self):
        print((self.name) + ":멍멍")
        
s = Dog("도기", 10, "말티즈", "하얀색")
s.bark()
s.run()

도기:멍멍
도기:헥헥


# class 변수
1. class 변수란? class 내에 선언되는 변수, 생성되는 

In [252]:
class People:
    no = 0 # class 멤버 변수
    def __init__(self, age = 1):
        People.no += 3
        self.age = age #instance 멤버 변수
        

In [255]:
p11 = People()
print(p11.no)
p12 = People()
print(p11.no)

15
18


# private 변수
1. 문법 : 언더바 두개로 선언
2. 권장사항 : 변수가 private인 경우 set/getXxx메소드 추가 구현 권장
   단, setXxx()는 유효성 검증

In [256]:
# 외부에서 호출 불가능한 데이터 관리
# 가령 age등은 1살 이산인 유효한 데이터에 한해서 저장 보장
# 유효성 검증 실행후 대입
# 주의사항 : 변수에는 직접 접근 불가
# 은닉성(encapsulation)
class People2:
    def __init__(self,name = "이이", age=0):
        self.name = name
        self.age = age
        

# 생성자와 소멸자
    1.init() :생성자(constructor)는 객체가 생성될 떄 객체를 기본값으로 초기화<br>
    

In [262]:
class People7:
    def __init__(self):
        print('생성자-객체 생성시 초기화 로직')
    def __del__(self):
        print('소멸자-자원반환 로직이 필요한 경우 개발')
    def __pr__(self):
        print('프린트를 합시다')

In [263]:
p7 = People7()

생성자-객체 생성시 초기화 로직


In [264]:
del p7

소멸자-자원반환 로직이 필요한 경우 개발


In [265]:
pr p7 # 이건 안됨

SyntaxError: invalid syntax (<ipython-input-265-cc355b46b2ea>, line 1)

# 특수 메소드
1. r"__init__"<br>
2. r"__str__"

In [337]:
class Book:
    def __init__(self,title,author,pages):
        self.title = title
        self.author = author
        self.pages = pages
           
    def __str__(self):
        return "제목 %s  저자 %s  페이지 %s"  % (self.title, self.author, self.pages)
    
    def __len__(self):
        return self.pages
    
book = Book("Data Structure","bookMan",200)
print(book)
print(len(book))

제목 Data Structure  저자 bookMan  페이지 200
200


In [267]:
class SpecialMethod:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __add__(self,addX):
        return self.x + addX

In [333]:
class SpecialMethod2:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __add__(self,you):
        return SpecialMethod2(self.x + you.x, self.y + you.y)
    
    def __eq__(self,you):
        print('__eq__ 호출 확인')
        return (self.x == you.x , self.y == you.y)
       #return (self.x ==you.x and self.y == you.y)
       #return (self.x ==you.x or self.y == you.y) 
    def __str__(self):
        return '(%d,%d)' % (self.x,self.y)

In [334]:
s21=SpecialMethod2(10,20)
s22=SpecialMethod2(10,40)
v =  s21 + s22
print(v)

(20,60)


In [335]:
print(s21 == s22)

__eq__ 호출 확인
(True, False)


(0,0)
